section!(
    PASTE,
    comment_paste,
    [
        CommentPasteTarget,
        CommentPasteState,
        CommentPastePrepareRequest,
        CommentPastePrepareResponse,
        CommentPasteSendRequest,
        CommentPasteMarkPastedRequest,
        CommentPasteReceipt,
    ]
);
