section!(
    SEARCH,
    context_search,
    [
        ContextSearchRequest,
        ContextSearchResult,
        ContextSearchResponse,
        ContextKnownRevision,
        ContextInvalidationState,
        ContextInvalidation,
        ContextInvalidationRequest,
        ContextInvalidationResponse,
    ]
);
