section!(
    CREDENTIALS,
    credentials,
    [
        ProviderAuthKind,
        ProviderCredentialState,
        ProviderCredentialStatus,
        ProviderCredentialStatusList,
        ProviderCredentialSetRequest,
        ProviderCredentialClearRequest,
    ]
);
