section!(
    QUOTA,
    quota,
    [
        QuotaProvider,
        QuotaProviderState,
        QuotaErrorCode,
        QuotaUnit,
        QuotaLevel,
        QuotaLimit,
        QuotaAccount,
        QuotaProviderStatus,
        QuotaStatusRequest,
        QuotaStatusResponse,
    ]
);
