//! Source-grounded TypeScript descriptors; the runtime owns validation semantics.
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::PathBuf;

use super::wire_model::{WireField, WireShape, WireTy, WireType};

#[path = "validators_index.rs"]
mod index;

pub(super) const GENERATED_HEADER: &str = "// This file was generated by cockpit-protocol export-typescript from the Rust DTO sources. Do not edit this file manually.\n";
const MAX_LINES: usize = 1_500;
const BODY_LINES: usize = 1_400;

struct Chunk<'a> {
    stem: String,
    types: Vec<&'a WireType>,
    bodies: Vec<String>,
}

/// Paths are relative to the directory containing the unchanged `v1.ts`.
pub(super) fn render(model: &[WireType]) -> Result<Vec<(PathBuf, String)>, String> {
    let chunks = descriptor_chunks(model)?;
    let mut locations = BTreeMap::new();
    for chunk in &chunks {
        for ty in &chunk.types {
            if locations
                .insert(ty.name.as_str(), chunk.stem.as_str())
                .is_some()
            {
                return Err(format!("duplicate wire type {}", ty.name));
            }
        }
    }
    let mut files = Vec::new();
    for chunk in &chunks {
        let contents = render_chunk(chunk, &locations)?;
        files.push((
            PathBuf::from(format!("validate/{}.ts", chunk.stem)),
            contents,
        ));
    }
    let stems: Vec<_> = chunks.iter().map(|chunk| chunk.stem.as_str()).collect();
    files.extend(index::render(model, &stems, &locations)?);
    files.push((
        PathBuf::from("validate/runtime.ts"),
        include_str!("validate_runtime.ts").to_owned(),
    ));
    let mut paths = BTreeSet::new();
    for (path, contents) in &files {
        if !paths.insert(path) {
            return Err(format!("duplicate generated path {}", path.display()));
        }
        if contents.lines().count() > MAX_LINES {
            return Err(format!(
                "generated file {} exceeds {MAX_LINES} lines",
                path.display()
            ));
        }
    }
    Ok(files)
}

fn descriptor_chunks(model: &[WireType]) -> Result<Vec<Chunk<'_>>, String> {
    let mut modules: BTreeMap<&str, Vec<&WireType>> = BTreeMap::new();
    for ty in model {
        if !ty
            .module
            .bytes()
            .all(|c| c.is_ascii_alphanumeric() || c == b'_')
            || ty.module.is_empty()
        {
            return Err(format!("invalid validator module {:?}", ty.module));
        }
        modules.entry(ty.module).or_default().push(ty);
    }
    let mut chunks = Vec::new();
    for (module, types) in modules {
        let mut number = 1;
        let mut chunk = Chunk {
            stem: module.to_owned(),
            types: Vec::new(),
            bodies: Vec::new(),
        };
        let mut lines = 0;
        for ty in types {
            let body = render_type(ty)?;
            let count = body.lines().count();
            if count > BODY_LINES {
                return Err(format!(
                    "descriptor {} exceeds the generated chunk budget",
                    ty.name
                ));
            }
            if lines + count > BODY_LINES && !chunk.types.is_empty() {
                chunks.push(chunk);
                number += 1;
                chunk = Chunk {
                    stem: format!("{module}_{number}"),
                    types: Vec::new(),
                    bodies: Vec::new(),
                };
                lines = 0;
            }
            lines += count;
            chunk.types.push(ty);
            chunk.bodies.push(body);
        }
        if !chunk.types.is_empty() {
            chunks.push(chunk);
        }
    }
    Ok(chunks)
}

fn render_chunk(chunk: &Chunk<'_>, locations: &BTreeMap<&str, &str>) -> Result<String, String> {
    let mut imports: BTreeMap<&str, BTreeSet<&str>> = BTreeMap::new();
    for ty in &chunk.types {
        let mut refs = BTreeSet::new();
        for field in all_fields(ty) {
            named_types(&field.ty, &mut refs);
        }
        for name in refs {
            let stem = locations
                .get(name)
                .ok_or_else(|| format!("{} references missing wire type {name}", ty.name))?;
            if *stem != chunk.stem {
                imports.entry(stem).or_default().insert(name);
            }
        }
    }
    let mut out = String::from(GENERATED_HEADER);
    out.push_str("import type * as V1 from \"../v1\";\n");
    out.push_str("import { struct, tagged, literal, req, opt, named, str, bool, f64, u8, u16, u32, u53, i53, integer, nullable, list, OMIT, type WireDescriptor } from \"./runtime\";\n");
    for (stem, names) in imports {
        let names = names
            .into_iter()
            .map(|name| format!("wire{name}"))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(out, "import {{ {names} }} from \"./{stem}\";").unwrap();
    }
    out.push('\n');
    for body in &chunk.bodies {
        out.push_str(body);
    }
    Ok(out)
}

fn render_type(ty: &WireType) -> Result<String, String> {
    let mut out = String::new();
    let name = &ty.name;
    let label = quote(name);
    match &ty.shape {
        WireShape::Struct(fields) => {
            writeln!(
                out,
                "export const wire{name}: WireDescriptor<V1.{name}> = struct<V1.{name}>({label}, {{"
            )
            .unwrap();
            render_fields(&mut out, fields, "  ")?;
            out.push_str("});\n\n");
        }
        WireShape::Literals(values) => {
            let values = values
                .iter()
                .map(|value| quote(value))
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(out, "export const wire{name}: WireDescriptor<V1.{name}> = literal<V1.{name}>({label}, [{values}]);\n").unwrap();
        }
        WireShape::Tagged { tag, variants } => {
            let tag = quote(tag);
            writeln!(out, "export const wire{name}: WireDescriptor<V1.{name}> = tagged<V1.{name}, {tag}>({label}, {tag}, {{").unwrap();
            for (variant, fields) in variants {
                writeln!(out, "  {}: {{", quote(variant)).unwrap();
                render_fields(&mut out, fields, "    ")?;
                out.push_str("  },\n");
            }
            out.push_str("});\n\n");
        }
    }
    Ok(out)
}

fn render_fields(out: &mut String, fields: &[WireField], indent: &str) -> Result<(), String> {
    for field in fields {
        let ty = if field.ts_nonnull {
            match &field.ty {
                WireTy::Option(inner) => inner.as_ref(),
                ty => ty,
            }
        } else {
            &field.ty
        };
        let check = render_check(ty);
        let mut options = Vec::new();
        if let Some(fill) = &field.fill {
            let json = serde_json::to_string(fill).map_err(|error| error.to_string())?;
            let value = if fill.is_object() || fill.is_array() {
                format!("() => ({json})")
            } else {
                json
            };
            options.push(format!("fill: {value}"));
        }
        if field.rust_omits {
            options.push("rustOmits: true".to_owned());
        }
        let options = if options.is_empty() {
            String::new()
        } else {
            format!(", {{ {} }}", options.join(", "))
        };
        let spec = if field.ts_optional {
            format!("opt({check}, OMIT{options})")
        } else {
            format!("req({check}{options})")
        };
        writeln!(out, "{indent}{}: {spec},", quote(&field.name)).unwrap();
    }
    Ok(())
}

fn render_check(ty: &WireTy) -> String {
    match ty {
        WireTy::Str => "str".to_owned(),
        WireTy::Bool => "bool".to_owned(),
        WireTy::F64 => "f64".to_owned(),
        WireTy::Int { min, max } => match (*min, *max) {
            (0, 255) => "u8".to_owned(),
            (0, 65_535) => "u16".to_owned(),
            (0, 4_294_967_295) => "u32".to_owned(),
            (0, 9_007_199_254_740_991) => "u53".to_owned(),
            (-9_007_199_254_740_991, 9_007_199_254_740_991) => "i53".to_owned(),
            _ => format!("integer({min}, {max})"),
        },
        WireTy::Option(inner) => format!("nullable({})", render_check(inner)),
        WireTy::List(inner) => format!("list({})", render_check(inner)),
        WireTy::Named(name) => format!("named(() => wire{name})"),
    }
}

fn named_types<'a>(ty: &'a WireTy, names: &mut BTreeSet<&'a str>) {
    match ty {
        WireTy::Named(name) => {
            names.insert(name);
        }
        WireTy::Option(inner) | WireTy::List(inner) => named_types(inner, names),
        _ => {}
    }
}

fn all_fields(ty: &WireType) -> impl Iterator<Item = &WireField> {
    let fields = match &ty.shape {
        WireShape::Struct(fields) => Some(fields),
        _ => None,
    };
    let variants = match &ty.shape {
        WireShape::Tagged { variants, .. } => Some(variants),
        _ => None,
    };
    fields.into_iter().flatten().chain(
        variants
            .into_iter()
            .flatten()
            .flat_map(|(_, fields)| fields),
    )
}

fn quote(value: &str) -> String {
    serde_json::to_string(value).expect("serializing a string cannot fail")
}
