// This file was generated by cockpit-protocol export-typescript from the Rust DTO sources. Do not edit this file manually.
export type WireReason = "shape" | "unknown_key" | "unknown_tag" | "refine";
export interface WireFrame { readonly type: string; readonly variant?: string; readonly field?: string; readonly index?: number }
export interface WireFailure { readonly reason: WireReason; readonly path: readonly WireFrame[]; readonly tag?: string; readonly refinement?: string; readonly array?: boolean }
export class WireFault extends Error {
  constructor(readonly failure: WireFailure) { super("Invalid wire value"); this.name = "WireFault"; }
}
export interface WireCheck<T = unknown> {
  readonly kind: "str" | "bool" | "number" | "named" | "nullable" | "list";
  readonly descriptor?: () => WireDescriptor<unknown>;
  readonly inner?: WireCheck<unknown>;
  readonly min?: number;
  readonly max?: number;
  readonly _output?: T;
}
export interface WireFieldMetadata {
  readonly check: WireCheck<unknown>;
  readonly optional: boolean;
  readonly rustOmits: boolean;
  readonly fill?: unknown | (() => unknown);
}
export interface WireFieldSpec<T, Optional extends boolean> extends WireFieldMetadata {
  readonly check: WireCheck<T>;
  readonly optional: Optional;
  readonly _exact?: (value: T) => T;
}
export interface WireDescriptor<T = unknown> {
  readonly type: string;
  readonly kind: "struct" | "tagged" | "literal";
  readonly fields?: Readonly<Record<string, WireFieldMetadata>>;
  readonly tag?: string;
  readonly variants?: Readonly<Record<string, Readonly<Record<string, WireFieldMetadata>>>>;
  readonly fieldNames?: readonly string[];
  readonly variantFieldNames?: Readonly<Record<string, readonly string[]>>;
  readonly values?: readonly string[];
  readonly _output?: T;
}
export type FieldSpec<T, K extends keyof T> = {} extends Pick<T, K>
  ? WireFieldSpec<Exclude<T[K], undefined>, true> : WireFieldSpec<T[K], false>;
export const OMIT = Symbol("wire omit");
export const str: WireCheck<string> = { kind: "str" };
export const bool: WireCheck<boolean> = { kind: "bool" };
export const f64: WireCheck<number> = { kind: "number" };
export const integer = (min: number, max: number): WireCheck<number> => ({ kind: "number", min, max });
export const u8 = integer(0, 255), u16 = integer(0, 65535), u32 = integer(0, 4294967295);
export const u53 = integer(0, Number.MAX_SAFE_INTEGER), i53 = integer(-Number.MAX_SAFE_INTEGER, Number.MAX_SAFE_INTEGER);
export const nullable = <T>(inner: WireCheck<T>): WireCheck<T | null> => ({ kind: "nullable", inner });
export const list = <T>(inner: WireCheck<T>): WireCheck<T[]> => ({ kind: "list", inner });
export const named = <T>(descriptor: () => WireDescriptor<T>): WireCheck<T> => ({ kind: "named", descriptor });
interface FillOptions { readonly fill?: unknown | (() => unknown); readonly rustOmits?: boolean }
export const req = <T>(check: WireCheck<T>, options: FillOptions = {}): WireFieldSpec<T, false> =>
  ({ check, optional: false, rustOmits: options.rustOmits ?? false, ...options });
export const opt = <T>(check: WireCheck<T>, _omit: typeof OMIT, options: FillOptions = {}): WireFieldSpec<T, true> =>
  ({ check, optional: true, rustOmits: options.rustOmits ?? false, ...options });
export function struct<T extends object>(type: string, fields: { readonly [K in keyof T]-?: FieldSpec<T, K> }): WireDescriptor<T> {
  return { type, kind: "struct", fields: fields as Readonly<Record<string, WireFieldMetadata>>, fieldNames: Object.keys(fields) };
}
export function literal<T extends string>(type: string, values: readonly T[]): WireDescriptor<T> {
  return { type, kind: "literal", values };
}
export function tagged<T extends Record<Tag, string>, Tag extends keyof T & string>(type: string, tag: Tag,
  variants: { readonly [V in T[Tag]]: { readonly [K in keyof Omit<Extract<T, Record<Tag, V>>, Tag>]-?: FieldSpec<Extract<T, Record<Tag, V>>, K> } }): WireDescriptor<T> {
  const entries = Object.values(variants) as Readonly<Record<string, WireFieldMetadata>>[];
  const fields: Record<string, WireFieldMetadata> = {};
  for (const key of Object.keys(entries[0] ?? {})) {
    if (entries.every(entry => Object.hasOwn(entry, key))) fields[key] = entries[0]![key]!;
  }
  const variantFieldNames: Record<string, readonly string[]> = {};
  for (const [variant, variantFields] of Object.entries(variants)) variantFieldNames[variant] = Object.keys(variantFields as object);
  return { type, kind: "tagged", tag, variants: variants as WireDescriptor<T>["variants"], fields, fieldNames: Object.keys(fields), variantFieldNames };
}
// The typed generated index checks each callback against its field/owner. Methods
// keep those checked callbacks assignable to the erased interpreter boundary.
type FieldRefinement = { refine(value: unknown): boolean | string }["refine"];
type OwnerRefinement = { refine(staged: unknown, original: unknown): boolean }["refine"];
export interface WirePolicy {
  readonly exact?: ReadonlySet<string>;
  readonly complete?: ReadonlySet<string>;
  readonly absent?: ReadonlySet<string>;
  readonly nullish?: ReadonlySet<string>;
  readonly materialize?: ReadonlySet<string>;
  readonly raw?: ReadonlySet<string>;
  readonly order?: Readonly<Record<string, readonly string[]>>;
  readonly emit?: Readonly<Record<string, readonly string[]>>;
  readonly lengths?: Readonly<Record<string, { readonly min?: number; readonly max?: number }>>;
  readonly fields?: Readonly<Record<string, FieldRefinement>>;
  readonly checks?: Readonly<Record<string, Readonly<Record<string, OwnerRefinement>>>>;
  readonly overrides?: Readonly<Record<string, WirePolicy>>;
}
const EMPTY: WirePolicy = {};
interface State {
  readonly descriptor: WireDescriptor<unknown>;
  readonly input: Record<string, unknown>;
  readonly policy: WirePolicy;
  readonly output: Record<string, unknown>;
  readonly done: Record<string, boolean>;
  readonly parent?: State;
  readonly parentAt?: WireFrame | string;
  deferredWireFailure?: WireFailure;
  children?: Record<string, State>;
  variant?: string;
  fields: Readonly<Record<string, WireFieldMetadata>>;
  names: readonly string[];
  finished?: boolean;
  projected?: Record<string, unknown>;
}
const owner = (s: State): string => s.variant === undefined ? s.descriptor.type : `${s.descriptor.type}[${s.variant}]`;
const frame = (s: State, field?: string, index?: number): WireFrame => ({ type: s.descriptor.type,
  ...(s.variant === undefined ? {} : { variant: s.variant }), ...(field === undefined ? {} : { field }), ...(index === undefined ? {} : { index }) });
function fault(reason: WireReason, at: WireFrame, tag?: string, refinement?: string, array = false): never {
  throw new WireFault({ reason, path: [at], ...(tag === undefined ? {} : { tag }), ...(refinement === undefined ? {} : { refinement }), ...(array ? { array: true } : {}) });
}
function withFrame<T>(at: WireFrame, work: () => T): T {
  try { return work(); } catch (error) {
    if (error instanceof WireFault) throw new WireFault({ ...error.failure, path: [at, ...error.failure.path] });
    throw error;
  }
}
function root(s: State): State {
  while (s.parent) s = s.parent;
  return s;
}
function deferHole(s: State, check: WireCheck<unknown>, at: WireFrame): void {
  const outer = root(s);
  if (outer.deferredWireFailure) return;
  const path: WireFrame[] = [at];
  while (check.kind === "nullable") check = check.inner!;
  if (check.kind === "named") path.push({ type: check.descriptor!().type });
  for (let child = s; child.parent; child = child.parent) {
    path.unshift(typeof child.parentAt === "string" ? frame(child.parent, child.parentAt) : child.parentAt!);
  }
  outer.deferredWireFailure = { reason: "shape", path };
}
function diagnostic(s: State, callback: (value: unknown, original: unknown) => boolean | string, value: unknown): boolean | string {
  try { return callback(value, s.input); } catch (error) {
    // A staged hole can make an identity callback dereference undefined. Keep
    // checking other fields; the public boundary still rejects the hole.
    if (error instanceof TypeError && root(s).deferredWireFailure
      && /^(Cannot read properties of undefined|Cannot destructure property .*undefined)/.test(error.message)) return true;
    throw error;
  }
}
function selected<T>(table: Readonly<Record<string, T>> | undefined, s: State, field: string): T | undefined {
  return table?.[`${owner(s)}.${field}`] ?? table?.[`${s.descriptor.type}.${field}`];
}
function has(set: ReadonlySet<string> | undefined, s: State, field?: string): boolean {
  return field === undefined ? !!(set?.has(owner(s)) || set?.has(s.descriptor.type))
    : !!(set?.has(`${owner(s)}.${field}`) || set?.has(`${s.descriptor.type}.${field}`));
}
function objectShape(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}
function record(value: unknown, descriptor: WireDescriptor<unknown>, policy: WirePolicy, parent?: State, parentAt?: WireFrame | string): State {
  if (!objectShape(value)) fault("shape", { type: descriptor.type }, undefined, undefined, Array.isArray(value));
  return { descriptor, input: value, policy, output: Object.create(null), done: Object.create(null), fields: descriptor.fields ?? {}, names: descriptor.fieldNames ?? [], parent, parentAt };
}
function tag(s: State, known: boolean): void {
  const key = s.descriptor.tag!;
  const value = s.input[key];
  if (typeof value !== "string") fault("shape", { type: s.descriptor.type, field: key });
  if (known && s.variant === undefined) {
    if (!Object.hasOwn(s.descriptor.variants!, value)) fault("unknown_tag", { type: s.descriptor.type, field: key }, value);
    s.variant = value;
    s.fields = s.descriptor.variants![value]!;
    s.names = s.descriptor.variantFieldNames![value]!;
    s.output[key] = value;
  }
}
function keys(s: State): void {
  const complete = has(s.policy.complete, s);
  if (!complete && !has(s.policy.exact, s)) return;
  for (const key of Object.keys(s.input)) {
    if (key !== s.descriptor.tag && !Object.hasOwn(s.fields, key)) fault("unknown_key", frame(s, key));
  }
  if (complete) {
    if (s.descriptor.tag && !Object.hasOwn(s.input, s.descriptor.tag)) fault("shape", { type: s.descriptor.type, field: s.descriptor.tag });
    for (const key of s.names) if (!Object.hasOwn(s.input, key)) fault("shape", frame(s, key));
  }
}
function shallow(value: unknown, check: WireCheck<unknown>, at: WireFrame, lengths?: { min?: number; max?: number }, strictRecord = false): void {
  if (check.kind === "nullable") { if (value === null) return; return shallow(value, check.inner!, at, lengths, strictRecord); }
  if (check.kind === "list") {
    if (!Array.isArray(value) || (lengths?.min !== undefined && value.length < lengths.min) || (lengths?.max !== undefined && value.length > lengths.max)) fault("shape", at);
  } else if (check.kind === "named") {
    const d = check.descriptor!();
    // Ordinary shallow checkpoints defer arrays to the mandatory deep check.
    // Record checkpoints preserve an earlier strict outer-object diagnostic.
    if (d.kind !== "literal" && (strictRecord || !Array.isArray(value)) && !objectShape(value)) fault("shape", at);
  }
}
function checked(value: unknown, check: WireCheck<unknown>, s: State, policy: WirePolicy, at: WireFrame, lengths?: { min?: number; max?: number }, preserveList = false): unknown {
  switch (check.kind) {
    case "str": if (typeof value !== "string") fault("shape", at); return value;
    case "bool": if (typeof value !== "boolean") fault("shape", at); return value;
    case "number":
      if (typeof value !== "number" || !Number.isFinite(value) || (check.min !== undefined && (!Number.isSafeInteger(value) || value < check.min || value > check.max!))) fault("shape", at);
      return value;
    case "nullable": return value === null ? null : checked(value, check.inner!, s, policy, at, lengths, preserveList);
    case "named": return withFrame(at, () => validate(value, check.descriptor!(), policy, s, at));
    case "list": {
      shallow(value, check, at, lengths);
      const entries = value as unknown[];
      const result = preserveList ? entries : new Array<unknown>(entries.length);
      for (let index = 0; index < entries.length; index++) {
        const itemAt = { ...at, index };
        if (!Object.hasOwn(entries, index)) { deferHole(s, check.inner!, itemAt); continue; }
        const entry = checked(entries[index], check.inner!, s, policy, itemAt, undefined, preserveList);
        if (!preserveList) result[index] = entry;
      }
      return result;
    }
  }
}
function missing(s: State, name: string, spec: WireFieldMetadata): unknown | typeof OMIT {
  if (spec.optional && !has(s.policy.materialize, s, name)) return OMIT;
  if (Object.hasOwn(spec, "fill")) return typeof spec.fill === "function" ? spec.fill() : spec.fill;
  fault("shape", frame(s, name));
}
function valueFor(s: State, name: string, spec: WireFieldMetadata): unknown | typeof OMIT {
  const value = s.input[name];
  if (has(s.policy.complete, s) && !Object.hasOwn(s.input, name)) fault("shape", frame(s, name));
  if (value === undefined && (spec.optional || spec.rustOmits || has(s.policy.absent, s, name) || has(s.policy.nullish, s, name) || has(s.policy.materialize, s, name))) return missing(s, name, spec);
  if (value === null && has(s.policy.nullish, s, name)) return missing(s, name, spec);
  return value;
}
function namedCheck(check: WireCheck<unknown>): WireDescriptor<unknown> | undefined {
  return check.kind === "nullable" ? namedCheck(check.inner!) : check.kind === "named" ? check.descriptor!() : undefined;
}
function field(s: State, name: string, mode?: "shallow" | "keys" | "record", tail?: string): void {
  if (s.descriptor.tag === name) { tag(s, false); return; }
  if (!s.fields[name] && s.descriptor.kind === "tagged" && s.variant === undefined) tag(s, true);
  const spec = s.fields[name];
  if (!spec) throw new Error(`Unknown wire checkpoint ${owner(s)}.${name}`);
  if (s.done[name] && !mode && !tail) return;
  const value = valueFor(s, name, spec);
  if (value === OMIT) { if (!mode && !tail) s.done[name] = true; return; }
  const childPolicy = selected(s.policy.overrides, s, name) ?? s.policy;
  const at = frame(s, tail ? `${name}.${tail.replace(/:(shallow|keys|record)$/, "")}` : name);
  const lengths = selected(s.policy.lengths, s, name);
  if (mode === "shallow" || mode === "record") { shallow(value, spec.check, at, lengths, mode === "record"); return; }
  const descriptor = namedCheck(spec.check);
  if ((mode === "keys" || tail) && value !== null) {
    if (!descriptor || descriptor.kind === "literal") throw new Error(`Non-object wire checkpoint ${owner(s)}.${name}`);
    const children = s.children ??= Object.create(null);
    const child = children[name] ??= withFrame(at, () => record(value, descriptor, childPolicy, s, name));
    withFrame(at, () => { if (mode === "keys") keys(child); else step(child, tail!); });
    return;
  }
  const result = s.children?.[name]
    ? withFrame(at, () => finish(s.children![name]!))
    : checked(value, spec.check, s, childPolicy, at, lengths, has(s.policy.raw, s, name));
  const refine = selected(s.policy.fields, s, name);
  if (refine) { const valid = diagnostic(s, refine, result); if (valid !== true) fault("refine", at, undefined, typeof valid === "string" ? valid : name); }
  s.output[name] = has(s.policy.raw, s, name) ? s.input[name] : result;
  s.done[name] = true;
}
function check(s: State, name: string): void {
  const callback = s.policy.checks?.[owner(s)]?.[name];
  if (!callback) throw new Error(`Unknown wire check ${owner(s)}.${name}`);
  if (!diagnostic(s, callback, s.output)) fault("refine", frame(s), undefined, name);
  s.done[`check:${name}`] = true;
}
function step(s: State, name: string): void {
  if (name === "keys") return keys(s);
  if (name === "tag" || name === "tag:known") return tag(s, name === "tag:known");
  if (name.startsWith("check:")) return check(s, name.slice(6));
  const dot = name.indexOf(".");
  if (dot !== -1) return field(s, name.slice(0, dot), undefined, name.slice(dot + 1));
  if (name.endsWith(":shallow")) return field(s, name.slice(0, -8), "shallow");
  if (name.endsWith(":keys")) return field(s, name.slice(0, -5), "keys");
  if (name.endsWith(":record")) return field(s, name.slice(0, -7), "record");
  field(s, name);
}
function fields(s: State): void {
  const order = s.policy.order?.[owner(s)];
  if (order) { for (const entry of order) step(s, entry); }
  else {
    keys(s);
    for (const name of s.names) if (!namedCheck(s.fields[name]!.check) && s.fields[name]!.check.kind !== "list") field(s, name);
    for (const name of s.names) field(s, name);
  }
}
function finish(s: State): unknown {
  if (s.finished) return has(s.policy.raw, s) ? s.input : s.projected!;
  if (s.descriptor.kind === "tagged") {
    const order = s.policy.order?.[s.descriptor.type];
    if (order) for (const entry of order) step(s, entry);
    else { tag(s, false); tag(s, true); }
    if (s.variant === undefined) tag(s, true);
  }
  fields(s);
  for (const name of Object.keys(s.policy.checks?.[owner(s)] ?? {})) if (!s.done[`check:${name}`]) check(s, name);
  s.finished = true;
  if (has(s.policy.raw, s)) return s.input;
  const emit = s.policy.emit?.[owner(s)];
  const output: Record<string, unknown> = {};
  if (!emit && s.descriptor.tag) output[s.descriptor.tag] = s.output[s.descriptor.tag];
  for (const entry of emit ?? s.names) {
    const name = entry === "tag" ? s.descriptor.tag! : entry;
    if (Object.hasOwn(s.output, name)) Object.defineProperty(output, name, { value: s.output[name], enumerable: true, writable: true, configurable: true });
  }
  s.projected = output;
  return output;
}
function validate<T>(value: unknown, descriptor: WireDescriptor<T>, policy: WirePolicy, parent?: State, parentAt?: WireFrame): T {
  if (descriptor.kind === "literal") {
    if (typeof value !== "string" || !descriptor.values!.includes(value)) fault("shape", { type: descriptor.type });
    return value as T;
  }
  return finish(record(value, descriptor, policy, parent, parentAt)) as T;
}
export function validateWire<T>(value: unknown, descriptor: WireDescriptor<T>, policy: WirePolicy = EMPTY): T {
  if (descriptor.kind === "literal") return validate(value, descriptor, policy);
  const s = record(value, descriptor, policy);
  const result = finish(s) as T;
  if (s.deferredWireFailure) throw new WireFault(s.deferredWireFailure);
  return result;
}
export function validateWireList<T>(value: unknown, descriptor: WireDescriptor<T>, policy: WirePolicy = EMPTY, lengths?: { min?: number; max?: number }): T[] {
  shallow(value, list(named(() => descriptor)), { type: descriptor.type }, lengths);
  const entries = value as unknown[];
  const result = new Array<T>(entries.length);
  for (let index = 0; index < entries.length; index++) {
    if (!Object.hasOwn(entries, index)) fault("shape", { type: descriptor.type, index });
    result[index] = withFrame({ type: descriptor.type, index }, () => validateWire(entries[index], descriptor, policy));
  }
  return result;
}
