#!/usr/bin/env node
import { spawn } from 'node:child_process';
import net from 'node:net';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import readline from 'node:readline';

const helperPath = path.join(path.dirname(fileURLToPath(import.meta.url)), 'browser-helper.mjs');
const child = spawn(process.env.NODE_BINARY || process.execPath, [helperPath], { stdio: ['pipe', 'pipe', 'inherit'] });
const lines = readline.createInterface({ input: child.stdout, crlfDelay: Infinity });
const pending = new Map(); let nextId = 1; let stopped = false; let frameSocket; let input = Buffer.alloc(0); let firstPacket; let latest; let packets = 0;
function assert(value, message) { if (!value) throw new Error(message); }
function wait(ms) { return new Promise((resolve) => setTimeout(resolve, ms)); }
function request(method, fields = {}) { const id = nextId++; return new Promise((resolve, reject) => { const timer = setTimeout(() => { pending.delete(id); reject(new Error(`timed out waiting for ${method}`)); }, 30_000); pending.set(id, { resolve, reject, timer }); child.stdin.write(`${JSON.stringify({ id, method, ...fields })}\n`); }); }
lines.on('line', (line) => { try { const response = JSON.parse(line); const pendingRequest = pending.get(response.id); if (!pendingRequest) return; pending.delete(response.id); clearTimeout(pendingRequest.timer); response.ok ? pendingRequest.resolve(response.result) : pendingRequest.reject(new Error(response.error || 'helper rejected request')); } catch {} });
child.once('exit', () => { for (const value of pending.values()) { clearTimeout(value.timer); value.reject(new Error('helper exited during smoke')); } pending.clear(); });
function maskedFrame(opcode, payload = Buffer.alloc(0)) { const mask = Buffer.from([0x11,0x22,0x33,0x44]); const encoded = Buffer.from(payload); for (let i = 0; i < encoded.length; i += 1) encoded[i] ^= mask[i % 4]; if (encoded.length > 125) throw new Error('smoke control payload was unexpectedly large'); return Buffer.concat([Buffer.from([0x80 | opcode, 0x80 | encoded.length]), mask, encoded]); }
function parsePacket(payload) { if (payload.length < 48) throw new Error('egress packet was shorter than MediaStream header'); const view = new DataView(payload.buffer, payload.byteOffset, payload.byteLength); const sequence = view.getUint32(8), width = view.getUint32(12), height = view.getUint32(16), bytes = view.getUint32(36); assert(view.getUint32(0) === 0x49505743 && view.getUint8(4) === 1 && view.getUint16(6) === 48, 'egress packet was not IPWC v1'); assert(view.getUint32(20) === 1, 'egress packet codec was not VP8'); assert(sequence > 0 && width > 0 && height > 0 && bytes > 0 && payload.length === 48 + bytes, 'egress packet fields were inconsistent'); return { sequence, width, height, keyframe: Boolean(view.getUint8(5) & 1), bytes };
}
function receive(chunk) { input = Buffer.concat([input, chunk]); while (input.length >= 2) { const first = input[0], second = input[1]; let head = 2, length = second & 0x7f; if (length === 126) { if (input.length < 4) return; length = input.readUInt16BE(2); head = 4; } else if (length === 127) { if (input.length < 10) return; length = Number(input.readBigUInt64BE(2)); head = 10; } if (input.length < head + length) return; const payload = input.subarray(head, head + length); input = input.subarray(head + length); if (first & 0x70 || second & 0x80) throw new Error('egress WebSocket framing was invalid'); if ((first & 15) === 2) { latest = parsePacket(payload); firstPacket ??= latest; packets += 1; frameSocket.write(maskedFrame(1, Buffer.from(`ack:${latest.sequence}`))); } } }
async function connectFrames(url) { const endpoint = new URL(url); assert(endpoint.protocol === 'ws:' && endpoint.hostname === '127.0.0.1', 'helper did not expose loopback frame WebSocket'); frameSocket = net.createConnection({ host: endpoint.hostname, port: Number(endpoint.port) }); await new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error('frame stream handshake timed out')), 8000); frameSocket.once('error', reject); frameSocket.once('connect', () => frameSocket.write(`GET ${endpoint.pathname}${endpoint.search} HTTP/1.1\r\nHost: ${endpoint.host}\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==\r\nSec-WebSocket-Version: 13\r\n\r\n`)); let handshake = Buffer.alloc(0); function receiveHandshake(chunk) { handshake = Buffer.concat([handshake, chunk]); const end = handshake.indexOf('\r\n\r\n'); if (end < 0) return; frameSocket.off('data', receiveHandshake); clearTimeout(timer); assert(handshake.subarray(0, end).toString('ascii').startsWith('HTTP/1.1 101'), 'frame endpoint rejected authenticated WebSocket'); frameSocket.on('data', receive); const rest = handshake.subarray(end + 4); if (rest.length) receive(rest); resolve(); } frameSocket.on('data', receiveHandshake); }); }
async function waitPacket(after = 0, timeout = 8000) { const deadline = performance.now() + timeout; while (!latest || latest.sequence <= after) { if (performance.now() > deadline) throw new Error('timed out waiting for real MediaStream ingress packet on egress'); await wait(25); } return latest; }
async function malformedUpgrade(url, pathname = '/frames') { const endpoint = new URL(url); const socket = net.createConnection({ host: endpoint.hostname, port: Number(endpoint.port) }); const response = await new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error('malformed upgrade was not rejected')), 4000); socket.once('error', reject); socket.once('connect', () => socket.write(`GET ${pathname}?token=wrong HTTP/1.1\r\nHost: ${endpoint.host}\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Key: malformed\r\nSec-WebSocket-Version: 13\r\n\r\n`)); socket.once('data', (chunk) => { clearTimeout(timer); resolve(chunk.toString('ascii')); }); }); socket.destroy(); assert(response.startsWith('HTTP/1.1 400'), `${pathname} accepted malformed or unauthenticated upgrade`); }
async function click(x, y) { await request('input', { event: { kind: 'mouseDown', x, y, button: 'left' } }); await request('input', { event: { kind: 'mouseUp', x, y, button: 'left' } }); }
async function eventually(description, callback, timeout = 6000) { const deadline = performance.now() + timeout; while (performance.now() < deadline) { const value = await callback(); if (value) return value; await wait(50); } throw new Error(`timed out waiting for ${description}`); }
async function run() {
  const normalized = await request('validateUrl', { url: 'google.de' }); assert(normalized.url === 'https://google.de/', 'bare navigation URL was not normalized');
  const start = await request('start'); assert(start.streamUrl?.startsWith('ws://127.0.0.1:'), 'start did not expose egress stream URL'); assert(start.pixelWidth > 0 && start.pixelHeight > 0, 'start omitted captured MediaStream geometry');
  await malformedUpgrade(start.streamUrl); await malformedUpgrade(start.streamUrl, '/ingress'); await connectFrames(start.streamUrl); await waitPacket(0); assert(firstPacket?.keyframe, 'first native-facing egress packet was not a VP8 keyframe'); assert(firstPacket.width === start.pixelWidth && firstPacket.height === start.pixelHeight, 'producer ingress dimensions disagreed with helper snapshot');
  const initialPackets = packets; let primed = false; for (const point of [[250,230],[300,250],[360,270],[400,210]]) { await click(...point); const state = await request('inspect'); if (state.activeElement === 'INPUT#name') { await request('input', { event: { kind: 'keyDown', key: 'Z', code: 'KeyZ', text: 'Z' } }); await request('input', { event: { kind: 'keyUp', key: 'Z', code: 'KeyZ' } }); primed = true; break; } } assert(primed, 'CDP input did not prime a visible target change'); await eventually('capture packet progress after target input', async () => packets > initialPackets); const beforeReloadPackets = packets; const reloaded = await request('reload'); assert(reloaded.title.includes('Interactive MediaStream Fixture'), 'reload did not preserve target page'); await eventually('capture packet progress after reload', async () => packets > beforeReloadPackets);
  let focused = false; for (const point of [[250,230],[300,250],[360,270],[400,210]]) { await click(...point); const state = await request('inspect'); if (state.activeElement === 'INPUT#name') { focused = true; break; } } assert(focused, 'CDP pointer input did not focus fixture name input');
  for (const [key, code] of [['A','KeyA'],['d','KeyD'],['a','KeyA']]) { await request('input', { event: { kind: 'keyDown', key, code, text: key } }); await request('input', { event: { kind: 'keyUp', key, code } }); }
  const greeted = await eventually('interactive greeting', async () => { for (const point of [[700,230],[760,250],[820,270],[880,230]]) { await click(...point); const state = await request('inspect'); if (state.fixtureStatus.includes('Hello, Ada!')) return state; } return undefined; }); assert(greeted.cursor === 'pointer', 'fixture button did not return pointer cursor');
  const beforeScroll = await request('inspect'); await request('input', { event: { kind: 'wheel', x: 500, y: 600, deltaX: 0, deltaY: 500 } }); const afterScroll = await request('inspect'); assert(afterScroll.scrollY > beforeScroll.scrollY, 'wheel did not scroll fixture');
  let selection; for (const y of [70, 110, 150, 190, 230, 270, 310, 350, 390, 430, 470, 510, 550, 590]) { await request('input', { event: { kind: 'mouseDown', x: 190, y, button: 'left', buttons: 1 } }); await request('input', { event: { kind: 'mouseMove', x: 760, y, buttons: 1 } }); await request('input', { event: { kind: 'mouseUp', x: 760, y, button: 'left', buttons: 0 } }); selection = await request('inspect'); if (selection.selectedText.length > 0) break; } assert(selection?.selectedText.length > 0, 'CDP drag did not select target text');
  const beforeNavigationPackets = packets; const navigated = await request('navigate', { url: 'https://google.de' }); assert(navigated.title.includes('Google'), `navigation did not reach Google (${navigated.title})`); const navigationHost = new URL(navigated.url).hostname; assert(/(^|\.)google\.(de|com)$/.test(navigationHost), `navigation did not reach a Google host (${navigated.url})`); await eventually('capture packet progress after google.de navigation', async () => packets > beforeNavigationPackets);
  console.log('interactive-browser-panel MediaStream smoke passed: trusted getDisplayMedia producer ingress, bounded VP8 IPWC egress, authenticated endpoints, reload, google.de navigation/reacquisition, pointer, typing, button, wheel, selection, inspect');
}
try { await run(); await request('stop'); stopped = true; } finally { if (!stopped) { try { await request('stop'); } catch {} } frameSocket?.destroy(); child.stdin.end(); lines.close(); if (child.exitCode === null) await new Promise((resolve) => child.once('exit', resolve)); }
