use crate::comment_paste::{
    CommentPasteMarkPastedRequest, CommentPastePrepareRequest, CommentPastePrepareResponse,
    CommentPasteReceipt, CommentPasteSendRequest, CommentPasteState, CommentPasteTarget,
};
use crate::context_assets::{
    ContextSnapshotCopyMode, ContextSnapshotMode, ContextSnapshotRequest, ContextSnapshotResponse,
};
use crate::context_media::{ContextMedia, ContextMediaRequest};
use crate::context_search::{
    ContextInvalidation, ContextInvalidationRequest, ContextInvalidationResponse,
    ContextInvalidationState, ContextKnownRevision, ContextSearchRequest, ContextSearchResponse,
    ContextSearchResult,
};
use crate::project_teardown::{
    WorkspaceTeardownAction, WorkspaceTeardownCompanionState, WorkspaceTeardownDirtyState,
    WorkspaceTeardownExecuteRequest, WorkspaceTeardownOutcome, WorkspaceTeardownOwnership,
    WorkspaceTeardownPreview, WorkspaceTeardownPreviewRequest, WorkspaceTeardownRecovery,
    WorkspaceTeardownRecoveryList, WorkspaceTeardownRecoveryState, WorkspaceTeardownResult,
    WorkspaceTeardownWorkspaceState,
};
use crate::review::{
    ReviewChangedFile, ReviewComparison, ReviewDiffLine, ReviewDiffLineKind, ReviewFileDiff,
    ReviewFileRequest, ReviewFileStatus, ReviewHunk, ReviewSide, ReviewSnapshot,
    ReviewSnapshotRequest,
};
use crate::sources::{
    SourceCapability, SourceEntry, SourceFreshness, SourceImportRequest, SourceImportResponse,
    SourceListRequest, SourceMaterializationStatus, SourceRefreshRequest,
};
use std::fs::{self, OpenOptions};
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::process;

use crate::comments::{
    CommentAnchor, CommentAttachment, CommentBatch, CommentBatchList, CommentBatchMutation,
    CommentBatchRequest, CommentBatchSummary, CommentCapture, CommentDraft, CommentFileRef,
    CommentLocation, CommentOwner, CommentPreview, CommentPreviewRequest, CommentRemoveRequest,
    CommentRequestScope, CommentReviewRef, CommentSourceState, CommentUpsertRequest,
};
use crate::context::{
    ContextDirectory, ContextDirectoryRequest, ContextDocument, ContextDocumentRequest,
    ContextEntry, ContextEntryKind, ContextLaunchRequest, ContextRoot, ContextRootKind,
    ContextSplitDirection, DetectionConfidence, ExtensionKind, PanePresentation,
    ReviewLaunchRequest,
};
use crate::projects::{
    ProjectArtifact, ProjectConfiguration, ProjectDiagnostic, ProjectLimits, ProjectProvider,
    RepositoryCandidate, RepositoryListResponse, WorkspaceOperation, WorkspaceOperationRequest,
    WorkspaceOperationState, WorkspaceOperationStep, WorkspaceOwnedResource,
    WorkspaceReconcileRequest, WorkspaceRecoveryAction, WorkspaceSetupMode, WorkspaceSetupPlan,
    WorkspaceSetupRequest,
};
use ts_rs::{Config, TS};

use crate::v1::{
    AgentSummary, CockpitCapabilities, CockpitMode, ErrorResponse, FocusKind, FocusRequest,
    FocusResponse, HerdrCompatibility, HerdrIdentity, LayoutPane, LayoutRect, PaneMoveDestination,
    PaneOutputResponse, PaneResizeDirection, PaneSplitDirection, PaneSummary, PaneZoomMode,
    ResourceMutationRequest, ResourceMutationResponse, SessionListResponse,
    SessionSnapshotResponse, SessionStreamMessage, SessionSummary, SpaceGitSummary, SpaceSummary,
    StatusResponse, TabLayout, TabSummary, TerminalCommand, TerminalMode, TerminalMouseButton,
    TerminalMouseKind, TerminalOpenRequest, TerminalOwnershipState, TerminalScrollDirection,
    TerminalScrollSource, TerminalStreamMessage,
};

const HEADER: &str = "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.";

/// Render every v1 DTO in a stable order using the declarations generated by ts-rs.
pub fn render_v1() -> String {
    let config = Config::default();
    let declarations = [
        CockpitMode::decl(&config),
        HerdrIdentity::decl(&config),
        HerdrCompatibility::decl(&config),
        CockpitCapabilities::decl(&config),
        StatusResponse::decl(&config),
        ErrorResponse::decl(&config),
        SpaceGitSummary::decl(&config),
        SpaceSummary::decl(&config),
        TabSummary::decl(&config),
        PaneSummary::decl(&config),
        AgentSummary::decl(&config),
        LayoutRect::decl(&config),
        LayoutPane::decl(&config),
        TabLayout::decl(&config),
        SessionSnapshotResponse::decl(&config),
        PaneOutputResponse::decl(&config),
        SessionSummary::decl(&config),
        SessionListResponse::decl(&config),
        FocusKind::decl(&config),
        FocusRequest::decl(&config),
        FocusResponse::decl(&config),
        PaneSplitDirection::decl(&config),
        PaneResizeDirection::decl(&config),
        PaneZoomMode::decl(&config),
        PaneMoveDestination::decl(&config),
        ResourceMutationRequest::decl(&config),
        ResourceMutationResponse::decl(&config),
        SessionStreamMessage::decl(&config),
        TerminalMode::decl(&config),
        TerminalOpenRequest::decl(&config),
        TerminalScrollDirection::decl(&config),
        TerminalScrollSource::decl(&config),
        TerminalMouseButton::decl(&config),
        TerminalMouseKind::decl(&config),
        TerminalCommand::decl(&config),
        TerminalOwnershipState::decl(&config),
        TerminalStreamMessage::decl(&config),
        ProjectLimits::decl(&config),
        ProjectProvider::decl(&config),
        ProjectConfiguration::decl(&config),
        RepositoryCandidate::decl(&config),
        ProjectDiagnostic::decl(&config),
        RepositoryListResponse::decl(&config),
        WorkspaceSetupMode::decl(&config),
        WorkspaceSetupRequest::decl(&config),
        ProjectArtifact::decl(&config),
        WorkspaceSetupPlan::decl(&config),
        WorkspaceOperationRequest::decl(&config),
        WorkspaceRecoveryAction::decl(&config),
        WorkspaceReconcileRequest::decl(&config),
        WorkspaceOperationState::decl(&config),
        WorkspaceOperationStep::decl(&config),
        WorkspaceOwnedResource::decl(&config),
        WorkspaceOperation::decl(&config),
        ExtensionKind::decl(&config),
        DetectionConfidence::decl(&config),
        ContextRootKind::decl(&config),
        ContextRoot::decl(&config),
        PanePresentation::decl(&config),
        ContextDirectoryRequest::decl(&config),
        ContextEntryKind::decl(&config),
        ContextEntry::decl(&config),
        ContextDirectory::decl(&config),
        ContextDocumentRequest::decl(&config),
        ContextDocument::decl(&config),
        ContextMediaRequest::decl(&config),
        ContextMedia::decl(&config),
        ContextSplitDirection::decl(&config),
        ContextLaunchRequest::decl(&config),
        ReviewLaunchRequest::decl(&config),
        CommentRequestScope::decl(&config),
        CommentOwner::decl(&config),
        CommentLocation::decl(&config),
        CommentAttachment::decl(&config),
        CommentFileRef::decl(&config),
        CommentSourceState::decl(&config),
        CommentReviewRef::decl(&config),
        CommentAnchor::decl(&config),
        CommentDraft::decl(&config),
        CommentBatch::decl(&config),
        CommentBatchSummary::decl(&config),
        CommentBatchList::decl(&config),
        CommentBatchRequest::decl(&config),
        CommentBatchMutation::decl(&config),
        CommentCapture::decl(&config),
        CommentUpsertRequest::decl(&config),
        CommentRemoveRequest::decl(&config),
        CommentPreviewRequest::decl(&config),
        CommentPreview::decl(&config),
        CommentPasteTarget::decl(&config),
        CommentPasteState::decl(&config),
        CommentPastePrepareRequest::decl(&config),
        CommentPastePrepareResponse::decl(&config),
        CommentPasteSendRequest::decl(&config),
        CommentPasteMarkPastedRequest::decl(&config),
        CommentPasteReceipt::decl(&config),
        WorkspaceTeardownAction::decl(&config),
        WorkspaceTeardownOwnership::decl(&config),
        WorkspaceTeardownDirtyState::decl(&config),
        WorkspaceTeardownWorkspaceState::decl(&config),
        WorkspaceTeardownCompanionState::decl(&config),
        WorkspaceTeardownPreviewRequest::decl(&config),
        WorkspaceTeardownExecuteRequest::decl(&config),
        WorkspaceTeardownPreview::decl(&config),
        WorkspaceTeardownOutcome::decl(&config),
        WorkspaceTeardownResult::decl(&config),
        WorkspaceTeardownRecoveryState::decl(&config),
        WorkspaceTeardownRecovery::decl(&config),
        WorkspaceTeardownRecoveryList::decl(&config),
        SourceCapability::decl(&config),
        SourceFreshness::decl(&config),
        SourceMaterializationStatus::decl(&config),
        SourceImportRequest::decl(&config),
        SourceListRequest::decl(&config),
        SourceRefreshRequest::decl(&config),
        SourceEntry::decl(&config),
        SourceImportResponse::decl(&config),
        ReviewSide::decl(&config),
        ReviewComparison::decl(&config),
        ReviewFileStatus::decl(&config),
        ReviewDiffLineKind::decl(&config),
        ReviewSnapshotRequest::decl(&config),
        ReviewChangedFile::decl(&config),
        ReviewSnapshot::decl(&config),
        ReviewFileRequest::decl(&config),
        ReviewDiffLine::decl(&config),
        ReviewHunk::decl(&config),
        ReviewFileDiff::decl(&config),
        ContextSnapshotRequest::decl(&config),
        ContextSnapshotResponse::decl(&config),
        ContextSnapshotMode::decl(&config),
        ContextSnapshotCopyMode::decl(&config),
        ContextSearchRequest::decl(&config),
        ContextSearchResult::decl(&config),
        ContextSearchResponse::decl(&config),
        ContextKnownRevision::decl(&config),
        ContextInvalidationState::decl(&config),
        ContextInvalidation::decl(&config),
        ContextInvalidationRequest::decl(&config),
        ContextInvalidationResponse::decl(&config),
    ]
    .into_iter()
    .map(|declaration| format!("export {declaration}"))
    .collect::<Vec<_>>()
    .join("\n\n");

    format!(
        "{HEADER}\n\n{}\n",
        declarations
            .lines()
            .map(str::trim_end)
            .collect::<Vec<_>>()
            .join("\n")
    )
}

/// Replace `path` with `contents` using a same-directory temporary file and rename.
pub fn write_atomic(path: &Path, contents: &[u8]) -> io::Result<()> {
    let parent = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));
    fs::create_dir_all(parent)?;

    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("generated.ts");
    let process_id = process::id();
    let mut temporary_path = PathBuf::new();
    let mut temporary_file = None;

    for attempt in 0..100u32 {
        let candidate = parent.join(format!(".{file_name}.{process_id}.{attempt}.tmp"));
        match OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&candidate)
        {
            Ok(file) => {
                temporary_path = candidate;
                temporary_file = Some(file);
                break;
            }
            Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
            Err(error) => return Err(error),
        }
    }

    let mut file = temporary_file.ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::AlreadyExists,
            "could not allocate a temporary path for atomic replacement",
        )
    })?;
    let result = (|| {
        file.write_all(contents)?;
        file.sync_all()?;
        drop(file);
        fs::rename(&temporary_path, path)
    })();

    if result.is_err() {
        let _ = fs::remove_file(&temporary_path);
    }
    result
}

/// Return whether `path` contains exactly the generated v1 bytes.
pub fn check(path: &Path) -> io::Result<bool> {
    match fs::read(path) {
        Ok(actual) => Ok(actual == render_v1().as_bytes()),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(false),
        Err(error) => Err(error),
    }
}
