use std::fs::{self, OpenOptions};
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::process;

use ts_rs::Config;

pub(crate) struct Section {
    pub module: &'static str,
    pub source: &'static str,
    pub decls: fn(&Config, &mut String),
    pub names: &'static [&'static str],
}

macro_rules! section {
    ($name:ident, $module:ident, [$($ty:ident),+ $(,)?]) => {
        pub(super) const $name: super::Section = super::Section {
            module: stringify!($module),
            source: include_str!(concat!("../", stringify!($module), ".rs")),
            decls: |config, declarations| {
                $(
                    super::append_declaration(
                        declarations,
                        &<crate::$module::$ty as ts_rs::TS>::decl(config),
                    );
                )+
            },
            names: &[$(stringify!($ty)),+],
        };
    };
}

mod browser;
mod browser_feedback;
mod browser_view;
mod comment_paste;
mod comments;
mod context;
mod context_media;
mod context_search;
mod credentials;
mod herdr_shell;
mod library;
mod notes;
mod orchestration;
mod project_defaults;
mod project_teardown;
mod projects;
mod quota;
mod review;
mod sources;
mod v1;
mod validators;
mod viewer;
mod widget;
mod wire_model;

pub(crate) const SECTIONS: &[&Section] = &[
    &v1::STATUS,
    &browser::BROWSER,
    &browser_feedback::FEEDBACK,
    &browser_view::VIEW,
    &v1::GIT_SUMMARIES,
    &herdr_shell::SHELL,
    &v1::SESSION_TERMINAL,
    &projects::CONFIGURATION,
    &library::LIBRARY,
    &notes::NOTES,
    &projects::REPOSITORIES,
    &project_defaults::DEFAULTS,
    &projects::WORKSPACE,
    &context::VIEWER_SOURCE,
    &viewer::VIEWER,
    &context::CONTEXT,
    &context_media::MEDIA,
    &comments::COMMENTS,
    &comment_paste::PASTE,
    &project_teardown::TEARDOWN,
    &sources::SOURCES,
    &review::REVIEW,
    &context_search::SEARCH,
    &credentials::CREDENTIALS,
    &quota::QUOTA,
    &widget::WIDGET,
    &orchestration::ORCHESTRATION,
];

const HEADER: &str = "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.";

/// Render every v1 DTO in a stable order using the declarations generated by ts-rs.
pub fn render_v1() -> String {
    let config = Config::default();
    let mut declarations = String::new();
    for section in SECTIONS {
        (section.decls)(&config, &mut declarations);
    }
    declarations.truncate(declarations.len() - 2);

    let mut output = String::with_capacity(HEADER.len() + declarations.len() + 3);
    output.push_str(HEADER);
    output.push_str("\n\n");
    for (index, line) in declarations.lines().enumerate() {
        if index > 0 {
            output.push('\n');
        }
        output.push_str(line.trim_end());
    }
    output.push('\n');
    output
}

fn append_declaration(declarations: &mut String, declaration: &str) {
    declarations.push_str("export ");
    declarations.push_str(declaration);
    declarations.push_str("\n\n");
}

/// Replace `path` with `contents` using a same-directory temporary file and rename.
pub fn write_atomic(path: &Path, contents: &[u8]) -> io::Result<()> {
    let parent = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));
    fs::create_dir_all(parent)?;

    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("generated.ts");
    let process_id = process::id();
    let mut temporary_path = PathBuf::new();
    let mut temporary_file = None;

    for attempt in 0..100u32 {
        let candidate = parent.join(format!(".{file_name}.{process_id}.{attempt}.tmp"));
        match OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&candidate)
        {
            Ok(file) => {
                temporary_path = candidate;
                temporary_file = Some(file);
                break;
            }
            Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
            Err(error) => return Err(error),
        }
    }

    let mut file = temporary_file.ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::AlreadyExists,
            "could not allocate a temporary path for atomic replacement",
        )
    })?;
    let result = (|| {
        file.write_all(contents)?;
        file.sync_all()?;
        drop(file);
        fs::rename(&temporary_path, path)
    })();

    if result.is_err() {
        let _ = fs::remove_file(&temporary_path);
    }
    result
}

/// Render the declarations and every source-derived validator artifact.
pub fn render_generated() -> io::Result<Vec<(PathBuf, String)>> {
    let model = wire_model::wire_model(SECTIONS).map_err(io::Error::other)?;
    let mut files = validators::render(&model).map_err(io::Error::other)?;
    let declarations = render_v1();
    if declarations.lines().count() > 1_500 {
        return Err(io::Error::other("generated file v1.ts exceeds 1500 lines"));
    }
    files.insert(0, (PathBuf::from("v1.ts"), declarations));
    Ok(files)
}

fn output_parent(path: &Path) -> &Path {
    path.parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."))
}

fn emitted_path(target: &Path, relative: &Path) -> PathBuf {
    if relative == Path::new("v1.ts") {
        target.to_owned()
    } else {
        output_parent(target).join(relative)
    }
}

// Only direct, generated .ts children of the exact validator output directory
// are eligible for pruning. Symlinks and user-authored files are never removed.
fn stale_validators(target: &Path, files: &[(PathBuf, String)]) -> io::Result<Vec<PathBuf>> {
    let directory = output_parent(target).join("validate");
    match fs::symlink_metadata(&directory) {
        Ok(metadata) if metadata.file_type().is_symlink() || !metadata.is_dir() => {
            return Err(io::Error::other(
                "validator output directory must not be a symlink",
            ));
        }
        Ok(_) => {}
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(error) => return Err(error),
    }
    let mut stale = Vec::new();
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let path = entry.path();
        if !entry.file_type()?.is_file()
            || path.extension().is_none_or(|extension| extension != "ts")
        {
            continue;
        }
        let relative = path
            .strip_prefix(output_parent(target))
            .map_err(io::Error::other)?;
        if files.iter().any(|(expected, _)| expected == relative) {
            continue;
        }
        let contents = fs::read(&path)?;
        if contents.starts_with(validators::GENERATED_HEADER.as_bytes()) {
            stale.push(path);
        }
    }
    stale.sort();
    Ok(stale)
}

/// Atomically replace every generated artifact, then prune recognized stale validators.
pub fn write_generated(path: &Path) -> io::Result<()> {
    let files = render_generated()?;
    let stale = stale_validators(path, &files)?;
    for (relative, _) in &files {
        let target = emitted_path(path, relative);
        if fs::symlink_metadata(&target).is_ok_and(|metadata| metadata.file_type().is_symlink()) {
            return Err(io::Error::other(format!(
                "generated output must not be a symlink: {}",
                target.display()
            )));
        }
    }
    for (relative, contents) in &files {
        write_atomic(&emitted_path(path, relative), contents.as_bytes())?;
    }
    for stale_path in stale {
        if fs::symlink_metadata(&stale_path)?.file_type().is_file()
            && fs::read(&stale_path)?.starts_with(validators::GENERATED_HEADER.as_bytes())
        {
            fs::remove_file(stale_path)?;
        }
    }
    Ok(())
}

/// Return drifted, missing and recognized stale paths without changing any file.
pub fn check_generated(path: &Path) -> io::Result<Vec<PathBuf>> {
    let files = render_generated()?;
    let mut drifted = stale_validators(path, &files)?;
    for (relative, contents) in &files {
        let target = emitted_path(path, relative);
        if fs::symlink_metadata(&target).is_ok_and(|metadata| metadata.file_type().is_symlink()) {
            drifted.push(target);
            continue;
        }
        match fs::read(&target) {
            Ok(actual) if actual == contents.as_bytes() => {}
            Ok(_) => drifted.push(target),
            Err(error) if error.kind() == io::ErrorKind::NotFound => drifted.push(target),
            Err(error) => return Err(error),
        }
    }
    drifted.sort();
    Ok(drifted)
}

/// Return whether the declarations and all sibling validator artifacts are current.
pub fn check(path: &Path) -> io::Result<bool> {
    check_generated(path).map(|drifted| drifted.is_empty())
}
