use std::fs::{self, OpenOptions};
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::process;

use ts_rs::{Config, TS};

use crate::v1::{
    AgentSummary, CockpitCapabilities, CockpitMode, ErrorResponse, FocusKind, FocusRequest,
    FocusResponse, HerdrCompatibility, HerdrIdentity, LayoutPane, LayoutRect, PaneMoveDestination,
    PaneOutputResponse, PaneResizeDirection, PaneSplitDirection, PaneSummary, PaneZoomMode,
    ResourceMutationRequest, ResourceMutationResponse, SessionListResponse,
    SessionSnapshotResponse, SessionStreamMessage, SessionSummary, SpaceGitSummary, SpaceSummary,
    StatusResponse, TabLayout, TabSummary, TerminalCommand, TerminalMode, TerminalMouseButton,
    TerminalMouseKind, TerminalOpenRequest, TerminalOwnershipState, TerminalScrollDirection,
    TerminalScrollSource, TerminalStreamMessage,
};

const HEADER: &str = "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.";

/// Render every v1 DTO in a stable order using the declarations generated by ts-rs.
pub fn render_v1() -> String {
    let config = Config::default();
    let declarations = [
        CockpitMode::decl(&config),
        HerdrIdentity::decl(&config),
        HerdrCompatibility::decl(&config),
        CockpitCapabilities::decl(&config),
        StatusResponse::decl(&config),
        ErrorResponse::decl(&config),
        SpaceGitSummary::decl(&config),
        SpaceSummary::decl(&config),
        TabSummary::decl(&config),
        PaneSummary::decl(&config),
        AgentSummary::decl(&config),
        LayoutRect::decl(&config),
        LayoutPane::decl(&config),
        TabLayout::decl(&config),
        SessionSnapshotResponse::decl(&config),
        PaneOutputResponse::decl(&config),
        SessionSummary::decl(&config),
        SessionListResponse::decl(&config),
        FocusKind::decl(&config),
        FocusRequest::decl(&config),
        FocusResponse::decl(&config),
        PaneSplitDirection::decl(&config),
        PaneResizeDirection::decl(&config),
        PaneZoomMode::decl(&config),
        PaneMoveDestination::decl(&config),
        ResourceMutationRequest::decl(&config),
        ResourceMutationResponse::decl(&config),
        SessionStreamMessage::decl(&config),
        TerminalMode::decl(&config),
        TerminalOpenRequest::decl(&config),
        TerminalScrollDirection::decl(&config),
        TerminalScrollSource::decl(&config),
        TerminalMouseButton::decl(&config),
        TerminalMouseKind::decl(&config),
        TerminalCommand::decl(&config),
        TerminalOwnershipState::decl(&config),
        TerminalStreamMessage::decl(&config),
    ]
    .into_iter()
    .map(|declaration| format!("export {declaration}"))
    .collect::<Vec<_>>()
    .join("\n\n");

    format!("{HEADER}\n\n{declarations}\n")
}

/// Replace `path` with `contents` using a same-directory temporary file and rename.
pub fn write_atomic(path: &Path, contents: &[u8]) -> io::Result<()> {
    let parent = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));
    fs::create_dir_all(parent)?;

    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("generated.ts");
    let process_id = process::id();
    let mut temporary_path = PathBuf::new();
    let mut temporary_file = None;

    for attempt in 0..100u32 {
        let candidate = parent.join(format!(".{file_name}.{process_id}.{attempt}.tmp"));
        match OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&candidate)
        {
            Ok(file) => {
                temporary_path = candidate;
                temporary_file = Some(file);
                break;
            }
            Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
            Err(error) => return Err(error),
        }
    }

    let mut file = temporary_file.ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::AlreadyExists,
            "could not allocate a temporary path for atomic replacement",
        )
    })?;
    let result = (|| {
        file.write_all(contents)?;
        file.sync_all()?;
        drop(file);
        fs::rename(&temporary_path, path)
    })();

    if result.is_err() {
        let _ = fs::remove_file(&temporary_path);
    }
    result
}

/// Return whether `path` contains exactly the generated v1 bytes.
pub fn check(path: &Path) -> io::Result<bool> {
    match fs::read(path) {
        Ok(actual) => Ok(actual == render_v1().as_bytes()),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(false),
        Err(error) => Err(error),
    }
}
