import { rename, unlink } from "node:fs/promises";
import { join } from "node:path";

const root = import.meta.dir;
const destination = join(root, "cockpit-orchestration.ts");
const banner = "// GENERATED by integrations/omp/bundle.ts from extension.ts. Do not edit; run: bun integrations/omp/bundle.ts";

function requireSelfContainedDefault(source: string): void {
  if (/^\s*import\b/m.test(source) || /\brequire\s*\(/.test(source)) {
    throw new Error("The deployed extension must not contain runtime imports.");
  }
  const exports = [...source.matchAll(/^\s*export\b[^;]*;/gm)];
  if (exports.length !== 1 || !/^\s*export\s*\{\s*[\w$]+\s+as\s+default\s*,?\s*\}\s*;$/.test(exports[0][0])) {
    throw new Error("The deployed extension must export only default.");
  }
}

async function writeAtomically(source: string): Promise<void> {
  const temporary = `${destination}.${process.pid}.${crypto.randomUUID()}.tmp`;
  try {
    await Bun.write(temporary, source);
    await rename(temporary, destination);
  } finally {
    await unlink(temporary).catch(error => {
      if (error.code !== "ENOENT") throw error;
    });
  }
}

async function bundle(): Promise<void> {
  const args = Bun.argv.slice(2);
  if (args.length > 1 || (args.length === 1 && args[0] !== "--check")) {
    throw new Error("Usage: bun integrations/omp/bundle.ts [--check]");
  }
  const result = await Bun.build({
    entrypoints: [join(root, "extension.ts")],
    root,
    target: "bun",
    format: "esm",
    minify: false,
    sourcemap: "none",
    splitting: false,
    banner,
  });
  if (!result.success) throw new AggregateError(result.logs, "OMP extension bundle failed.");
  if (result.outputs.length !== 1) throw new Error("The deployed extension must be a single bundle output.");
  const source = await result.outputs[0].text();
  requireSelfContainedDefault(source);
  const existing = Bun.file(destination);
  const identical = await existing.exists() && await existing.text() === source;
  if (args[0] === "--check") {
    if (!identical) throw new Error("OMP extension bundle is stale; run: bun integrations/omp/bundle.ts");
  } else if (!identical) {
    await writeAtomically(source);
  }
}

await bundle();
