import type { TypedWirePolicy } from "../protocol/generated/validate";
import type { WireFailure } from "../protocol/generated/validate/runtime";
import { definePolicy, messageTable } from "./wire";

const nonempty = (v: string) => v.length > 0;
const id = (v: string) => v.length > 0 && v.length <= 512;
const nullableId = (v: string | null) => v === null || id(v);
const text = (v: string) => v.length <= 64 * 1024;
const positive = (v: number) => v > 0;
const ratio = (v: number | null) => v === null || (v > 0 && v < 1);
const ids = (v: readonly string[]) => v.every(id);
const nonemptyIds = (v: readonly string[]) => v.every(nonempty);
const hash = (v: string) => /^[0-9a-f]{24}$/.test(v);
const base64 = (v: string) => v.length % 4 === 0 && /^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(v);
const sessionId = (v: string) => v.length > 0 && v.length <= 96 && /^[A-Za-z0-9_-]+$/.test(v);
const resourceId = (v: string) => v.length > 0 && v.length <= 128 && /^[A-Za-z0-9:_-]+$/.test(v);
function ownerTag(f: WireFailure, type: string): string | undefined {
  for (let i = f.path.length - 1; i >= 0; i--) {
    if (f.path[i].type === type) return f.path[i].variant ?? f.tag;
  }
  return undefined;
}
const unknownTag = (label: string, otherwise: string) => (f: WireFailure) => f.reason === "unknown_tag" ? `${label}: ${f.tag}` : otherwise;
const checkedMessage = (messages: Readonly<Record<string, string>>, otherwise: string) => (f: WireFailure) => messages[f.refinement ?? ""] ?? otherwise;
// Array records are invalid; record-boundary failures receive the type-specific label.
const arrayRecordMessage = (type: string, arrayLabel: string, otherwise: string) => (f: WireFailure) => {
  const failed = f.path[f.path.length - 1];
  return f.reason === "shape" && f.array && failed?.type === type && failed.field === undefined ? arrayLabel : otherwise;
};

// Messages belong to the parser that originally detected the fault, not to DTO leaf primitives.
const messages = {
  ErrorResponse: "Error response is malformed",
  StatusResponse: "Status response is missing required fields",
  CockpitCapabilities: "Status response capabilities are invalid",
  HerdrCompatibility: unknownTag("Unknown Herdr status", "Status response is missing required fields"),
  "HerdrCompatibility[compatible]": "Compatible Herdr status has no valid identity",
  "HerdrCompatibility[incompatible]": "Incompatible Herdr status is missing required fields",
  "HerdrCompatibility[unavailable]": "Unavailable Herdr status is missing required fields",
  BrowserTarget: "Browser target is malformed",
  BrowserAction: (f: WireFailure) => f.reason === "unknown_tag" ? "Unknown browser action" : "Browser action is malformed",
  "BrowserAction[open]": "Browser open URL is malformed",
  "BrowserAction[open_fresh]": "Browser open URL is malformed",
  BrowserAssociation: "Browser association is malformed",
  BrowserRequest: arrayRecordMessage("BrowserRequest", "Browser target is malformed", "Browser request is malformed"),
  BrowserResponse: "Browser response is malformed",
  BrowserWorkScope: "Browser work scope is malformed",
  BrowserCleanupScope: "Browser cleanup scope is malformed",
  BrowserCleanupFailure: "Browser cleanup failure is malformed",
  BrowserCleanupStatus: "Browser cleanup status is malformed",
  BrowserCleanupRetryRequest: "Browser cleanup retry request is malformed",
  BrowserViewViewportRequest: "Browser view viewport request is malformed",
  BrowserViewOpenRequest: "Browser view open request is malformed",
  BrowserViewIdentity: "Browser view identity is malformed",
  BrowserViewTargetSummary: "Browser view target summary is malformed",
  BrowserViewTargetKind: "Browser view target kind is malformed",
  BrowserViewDocumentState: "Browser view document state is malformed",
  BrowserViewViewportState: "Browser view viewport state is malformed",
  BrowserViewNavigationState: "Browser view navigation state is malformed",
  BrowserViewCursorState: "Browser view cursor state is malformed",
  BrowserViewCursor: "Browser view cursor is malformed",
  BrowserViewFocusState: "Browser view focus state is malformed",
  BrowserViewBlocker: "Browser view blocker is malformed",
  BrowserViewBlockerKind: "Browser view blocker kind is malformed",
  BrowserViewCapabilities: "Browser view capabilities are malformed",
  BrowserViewControlState: "Browser view control state is malformed",
  BrowserViewFrameEnvelopeV2: "Browser view frame envelope is malformed",
  BrowserViewFrameGrant: "Browser view frame grant is malformed",
  BrowserViewFrameDescriptor: "Browser view frame descriptor is malformed",
  BrowserViewSnapshot: checkedMessage({ grant_stream: "Browser view frame grant belongs to another stream" }, "Browser view snapshot is malformed"),
  BrowserViewEventMetadata: "Browser view event metadata is malformed",
  BrowserViewEvent: unknownTag("Unknown browser view event type", "Browser view event is malformed"),
  "BrowserViewEvent[attached]": checkedMessage({ attached_identity: "Attached browser view snapshot identity is malformed" }, "Browser view event is malformed"),
  "BrowserViewEvent[targets_changed]": "Browser view targets event is malformed",
  "BrowserViewEvent[frame_transport_revoked]": "Browser view frame transport event is malformed",
  "BrowserViewEvent[failed]": "Browser view failure event is malformed",
  "BrowserViewEvent[closed]": "Browser view closed event is malformed",
  BrowserViewLocation: "Browser view location is malformed",
  BrowserViewDocumentCommandContext: "Browser view document context is malformed",
  BrowserViewPointerInput: "Browser view pointer input is malformed",
  BrowserViewWheelInput: "Browser view wheel input is malformed",
  BrowserViewKeyboardInput: "Browser view keyboard input is malformed",
  BrowserViewTextInput: "Browser view text input is malformed",
  BrowserViewCompositionInput: "Browser view composition input is malformed",
  BrowserViewClipboardCommand: "Browser view clipboard command is malformed",
  BrowserViewNavigationCommand: "Browser view navigation command is malformed",
  BrowserViewTabCommand: "Browser view tab command is malformed",
  BrowserViewDialogCommand: "Browser view dialog command is malformed",
  BrowserViewFileCommand: "Browser view file command is malformed",
  BrowserViewDownloadCommand: "Browser view download command is malformed",
  BrowserViewPermissionCommand: "Browser view permission command is malformed",
  BrowserViewInspectResult: "Browser view inspection result is malformed",
  BrowserViewInspectCommand: "Browser view inspection command is malformed",
  BrowserViewCaptureCommand: "Browser view capture command is malformed",
  BrowserViewDraftAnnotation: "Browser view draft annotation is malformed",
  BrowserViewDraftState: "Browser view draft state is malformed",
  BrowserViewDraftEditorState: "Browser view draft state is malformed",
  BrowserViewPendingCapture: "Browser pending capture is malformed",
  BrowserViewDraftInventory: "Browser draft inventory outcome is malformed",
  BrowserViewCaptureOutcome: "Browser capture outcome is malformed",
  BrowserCaptureSaved: "Browser saved capture is malformed",
  BrowserViewDraftCommand: "Browser view draft command is malformed",
  BrowserCaptureSubmission: "Browser capture save command is malformed",
  BrowserInlineCaptureProvenance: "Browser capture save command is malformed",
  BrowserDraftRecoveryRequest: "Browser draft recovery request is malformed",
  BrowserDraftRecoveryAction: arrayRecordMessage("BrowserDraftRecoveryAction", "Browser draft recovery request is malformed", "Browser draft recovery action is malformed"),
  BrowserViewCommand: unknownTag("Unknown browser view command type", "Browser view command is malformed"),
  "BrowserViewCommand[release_control]": "Browser view release command is malformed",
  "BrowserViewCommand[dialog]": "Browser view dialog command is malformed",
  "BrowserViewCommand[file]": "Browser view file command is malformed",
  "BrowserViewCommand[download]": "Browser view download command is malformed",
  "BrowserViewCommand[permission]": "Browser view permission command is malformed",
  "BrowserViewCommand[draft]": "Browser view draft command is malformed",
  BrowserViewCommandRequest: "Browser view command request is malformed",
  BrowserViewCommandOutcome: unknownTag("Unknown browser view command outcome type", "Browser view command outcome is malformed"),
  "BrowserViewCommandOutcome[capture_prepared]": "Browser view capture outcome is malformed",
  "BrowserViewCommandOutcome[clipboard]": "Browser view clipboard outcome is malformed",
  BrowserViewCommandResponse: unknownTag("Unknown browser view command response status", "Browser view command response is malformed"),
  "BrowserViewCommandResponse[rejected]": "Browser view command failure is malformed",
  "BrowserViewCommandResponse[outcome_unknown]": "Browser view command failure is malformed",
  "BrowserViewCommandResponse[unsupported]": "Browser view unsupported response is malformed",
  "BrowserViewCommandResponse[stale]": "Browser view stale response is malformed",
  BrowserPoint: "Browser feedback point is malformed",
  BrowserRect: "Browser feedback bounds are malformed",
  BrowserElementEvidence: "Browser element evidence is malformed",
  BrowserPageEvidence: "Browser page evidence is malformed",
  BrowserAnnotation: "Browser annotation is malformed",
  BrowserCaptureContext: "Browser capture context is malformed",
  BrowserFeedbackCapture: "Browser feedback capture is malformed",
  BrowserFeedbackResponse: "Browser feedback response is malformed",
  BrowserFeedbackRequest: arrayRecordMessage("BrowserFeedbackRequest", "Browser work scope is malformed", "Browser feedback request is malformed"),
  BrowserFeedbackAckRequest: "Browser feedback acknowledgement request is malformed",
  BrowserFeedbackImageRequest: "Browser feedback image request is malformed",
  BrowserFeedbackSendRequest: "Browser feedback send request is malformed",
  BrowserFeedbackDeliveryStatus: "Browser feedback delivery status is malformed",
  BrowserFeedbackLookup: (f: WireFailure) => f.array && f.path.some(p => p.type === "BrowserFeedbackLookup" && p.field === undefined) ? "Browser response is malformed" : f.path.some(p => p.type === "BrowserFeedbackLookup" && p.field === "deliveries") ? "Browser feedback deliveries are malformed" : "Browser feedback lookup is malformed",
  BrowserFeedbackImage: "Browser feedback image is malformed",
  CommentPasteTarget: "Browser feedback target is malformed",
  BrowserFeedbackSendResponse: "Browser feedback send response is malformed",
  BrowserFeedbackAck: "Browser feedback acknowledgement response is malformed",
  HerdrShellState: "Herdr shell state is malformed",
  HerdrCommand: "Herdr command is malformed",
  HerdrPopup: "Herdr popup is malformed",
  HerdrPopupSize: "Herdr popup size is malformed",
  SessionSnapshotResponse: "Session snapshot response is missing required fields",
  SpaceGitUpstream: "Space Git upstream is malformed",
  SpaceGitCheckout: "Space Git checkout is malformed",
  SpaceGitStatusResponse: "Space Git status response is missing required fields",
  SpaceGitStatus: "Space Git status is malformed",
  SpaceGitActionOutcome: "Space Git action outcome is malformed",
  SpaceGitActionResponse: "Space Git action response is missing required fields",
  SessionSummary: "Session summary is missing required fields",
  SessionListResponse: "Session list response is missing required fields",
  FocusRequest: "Focus request is missing required fields",
  FocusResponse: "Focus response is missing required fields",
  PaneMoveDestination: (f: WireFailure) => ownerTag(f, "PaneMoveDestination") === undefined ? "Pane move destination is malformed" : `Unknown or malformed pane move destination: ${ownerTag(f, "PaneMoveDestination")}`,
  ResourceMutationRequest: (f: WireFailure) => f.reason === "unknown_tag" ? `Unknown resource mutation type: ${f.tag}` : ownerTag(f, "ResourceMutationRequest") === undefined ? "Resource mutation request is malformed" : `Resource mutation ${ownerTag(f, "ResourceMutationRequest")} is missing required fields`,
  CreatedPane: "Created pane identity is malformed",
  ResourceMutationResponse: checkedMessage({ snapshot_session: "Resource mutation snapshot belongs to another session", created_identity: "Created pane does not match mutation snapshot identity" }, "Resource mutation response is missing required fields"),
  SessionStreamMessage: "Session stream message is malformed",
  TerminalOpenRequest: checkedMessage({ herdr_ids: "Terminal open request has an invalid target" }, "Terminal open request is malformed"),
  TerminalCommand: (f: WireFailure) => f.reason === "unknown_tag" ? "Terminal command has an unknown type" : "Terminal command is malformed",
  "TerminalCommand[terminal.input]": "Terminal input requires exactly one of text or bytes",
  "TerminalCommand[terminal.resize]": "Terminal resize command is malformed",
  "TerminalCommand[terminal.scroll]": "Terminal scroll command is malformed",
  "TerminalCommand[terminal.mouse]": "Terminal mouse command is malformed",
  TerminalStreamMessage: (f: WireFailure) => f.reason === "unknown_tag" ? "Terminal stream message has an unknown type" : "Terminal stream message is malformed",
  "TerminalStreamMessage[ownership]": "Terminal ownership message is malformed",
  "TerminalStreamMessage[mouse_mode]": "Terminal mouse mode message is malformed",
  "TerminalStreamMessage[frame]": checkedMessage({ sequence: "Terminal frame sequence is malformed" }, "Terminal frame message is malformed"),
  "TerminalStreamMessage[closed]": "Terminal closed message is malformed",
  "TerminalStreamMessage[disconnected]": "Terminal failure message is malformed",
  "TerminalStreamMessage[error]": "Terminal failure message is malformed",
};
const absorb = new Set([
  "HerdrCompatibility[compatible].identity", "HerdrCompatibility[incompatible].identity",
  "BrowserViewEvent[targets_changed].targets", "BrowserViewDraftState.annotations", "BrowserViewDraftState.editor",
  "BrowserViewDraftInventory.drafts", "SessionListResponse.sessions", "SessionStreamMessage[snapshot].snapshot",
  "BrowserPageEvidence.viewport", "BrowserDraftRecoveryAction[set_editor].editor",
  "BrowserViewCommand[draft].context.target_id", "BrowserDraftRecoveryRequest.action.type",
  "BrowserCaptureContext.inline_provenance",
]);

// Names-only sequencing preserves guards before nested parser calls (base CockpitClient.ts:563–1914).
const order: NonNullable<TypedWirePolicy["order"]> = {
  StatusResponse: ["protocol_version", "cockpit_version", "capabilities", "herdr", "mode"],
  "HerdrCompatibility[incompatible]": ["code", "message", "identity"],
  BrowserRequest: ["target", "action"],
  BrowserResponse: ["association:shallow", "connection", "message", "cleanup", "cleanup_reason", "association"],
  BrowserCleanupFailure: ["association_key", "reason", "unproven_paths", "scope"],
  BrowserViewOpenRequest: ["client_id", "takeover", "target", "viewport"],
  BrowserViewTargetSummary: ["target_id", "title", "url", "order", "opener_target_id", "can_close", "kind"],
  BrowserViewCursorState: ["target_id", "pointer_sample_sequence", "document_generation", "viewport_revision", "cursor"],
  BrowserViewBlocker: ["blocker_id", "message", "default_prompt", "target_id", "document_generation", "cancellable", "kind"],
  BrowserViewFrameGrant: ["view_id", "stream_epoch", "grant", "expires_at", "envelope"],
  BrowserViewSnapshot: ["metadata_sequence", "targets:shallow", "displayed_target_id", "identity", "targets", "document", "viewport", "navigation", "cursor", "blocker", "frame_grant", "check:grant_stream", "focus", "capabilities", "control"],
  BrowserViewEvent: ["tag", "metadata", "tag:known"],
  "BrowserViewEvent[targets_changed]": ["targets", "displayed_target_id"],
  BrowserViewInspectResult: ["frame_id", "frame_generation", "pointer_sample_sequence", "inspectable", "freshness", "limitation", "location", "bounds", "evidence"],
  BrowserViewInspectCommand: ["pointer_sample_sequence", "x", "y", "location"],
  BrowserViewCaptureCommand: ["draft_id", "draft_revision", "annotation_ids", "capture_as_shown", "location"],
  BrowserViewDraftAnnotation: ["id", "kind", "color", "points:shallow", "comment", "points", "bounds", "evidence"],
  BrowserViewDraftState: ["draft_id", "target_id", "document_generation", "revision", "annotations", "freshness", "stale", "editor"],
  BrowserViewDraftInventory: ["drafts", "active_draft_limit", "pending_capture:shallow", "pending_capture"],
  "BrowserViewDraftCommand[save_capture]": ["submission:shallow", "annotation_ids", "provenance:shallow", "submission.association_key", "submission.browser_instance", "submission.capture_id", "submission.annotations:shallow", "submission.png_base64", "provenance", "submission"],
  BrowserCaptureSubmission: ["association_key", "browser_instance", "capture_id", "annotations:shallow", "png_base64", "page", "annotations"],
  BrowserDraftRecoveryRequest: ["action:shallow", "action.type", "action", "scope"],
  "BrowserDraftRecoveryAction[upsert_annotation]": ["draft_id", "expected_revision", "annotation:shallow", "annotation"],
  "BrowserViewCommand[resize]": ["context", "viewport"],
  "BrowserViewCommand[pointer]": ["location", "input"],
  "BrowserViewCommand[wheel]": ["location", "input"],
  "BrowserViewCommand[keyboard]": ["context", "input"],
  "BrowserViewCommand[text]": ["context", "input"],
  "BrowserViewCommand[composition]": ["context", "input"],
  "BrowserViewCommand[clipboard]": ["context", "command"],
  "BrowserViewCommand[navigation]": ["context", "command"],
  "BrowserViewCommand[draft]": ["context.target_id", "draft_id", "expected_revision", "context", "command"],
  BrowserViewCommandResponse: ["tag", "view_id", "stream_epoch", "request_id", "tag:known"],
  BrowserAnnotation: ["id", "kind", "comment", "color", "points:shallow", "bounds:shallow", "element:shallow", "points", "bounds", "element"],
  BrowserFeedbackCapture: ["id", "context:shallow", "page:shallow", "annotations:shallow", "pending_ids", "image_path", "context", "page", "annotations"],
  BrowserFeedbackResponse: ["captures:shallow", "pending_count", "retention_seconds", "captures"],
  BrowserFeedbackAckRequest: ["ids", "scope"],
  BrowserFeedbackImageRequest: ["capture_id", "scope"],
  BrowserFeedbackSendRequest: ["check:no_recipient", "ids", "operation_id", "acknowledge_duplicate_risk", "scope"],
  BrowserFeedbackLookup: ["deliveries:shallow", "browser", "feedback", "deliveries", "drafts"],
  BrowserFeedbackSendResponse: ["operation_id", "state", "target:shallow", "acknowledged_ids", "pending_count", "message", "target"],
  HerdrShellState: ["status", "commands:shallow", "prefix_bindings", "error", "commands", "popup"],
  HerdrPopup: ["terminal_id", "title", "width", "height"],
  SessionSnapshotResponse: ["session_id", "server_instance", "version", "protocol", "focused_space_id", "focused_tab_id", "focused_pane_id", "spaces", "tabs", "panes", "agents", "herdr_shell"],
  ResourceMutationResponse: ["session_id", "snapshot", "check:snapshot_session", "created", "check:created_identity"],
  SessionStreamMessage: ["tag", "session_id", "generation", "sequence", "tag:known"],
  TerminalOpenRequest: ["session_id", "pane_id", "target_kind", "mode", "takeover", "cols", "rows", "cell_width_px", "cell_height_px", "check:herdr_ids"],
  TerminalStreamMessage: ["tag", "session_id", "pane_id", "stream_id", "tag:known"],
};

const wire: TypedWirePolicy = {
  exact: new Set(["BrowserCleanupStatus"]),
  // These were casts or pass-through arrays in the original parser; validation still runs.
  raw: new Set([
    "HerdrIdentity", "BrowserAction", "BrowserAssociation", "BrowserElementEvidence", "CommentPasteTarget", "BrowserPageEvidence.viewport",
    "SessionSnapshotResponse.spaces", "SessionSnapshotResponse.tabs", "SessionSnapshotResponse.panes", "SessionSnapshotResponse.agents",
    "BrowserCleanupFailure.unproven_paths", "BrowserViewFileCommand[choose].selection_ids",
    "BrowserViewCaptureCommand.annotation_ids", "BrowserViewPendingCapture.annotation_ids", "BrowserCaptureSaved.annotation_ids",
    "BrowserViewDraftCommand[save_capture].annotation_ids", "BrowserFeedbackCapture.pending_ids",
    "BrowserFeedbackAckRequest.ids", "BrowserFeedbackSendRequest.ids", "BrowserFeedbackDeliveryStatus.selected_ids",
    "BrowserFeedbackSendResponse.acknowledged_ids", "BrowserFeedbackAck.acknowledged_ids",
    "HerdrShellState.prefix_bindings", "HerdrCommand.binding_labels", "ResourceMutationRequest[space_move_block].space_ids",
  ]),
  absent: new Set(["BrowserViewPendingCapture.last_error", "BrowserViewDraftEditorState.note_annotation_id", "BrowserViewDraftEditorState.note_text", "BrowserFeedbackLookup.deliveries", "BrowserCaptureContext.inline_provenance", "HerdrPopup.width", "HerdrPopup.height"]),
  nullish: new Set(["BrowserFeedbackLookup.drafts", "ResourceMutationResponse.created"]),
  materialize: new Set(["BrowserPageEvidence.tab_id"]),
  order,
  emit: {
    "HerdrCompatibility[incompatible]": ["tag", "identity", "code", "message"],
    BrowserViewCursorState: ["cursor", "pointer_sample_sequence", "target_id", "document_generation", "viewport_revision"],
    BrowserViewSnapshot: ["identity", "metadata_sequence", "targets", "displayed_target_id", "document", "viewport", "navigation", "cursor", "focus", "blocker", "capabilities", "control", "frame_grant"],
    HerdrShellState: ["status", "commands", "prefix_bindings", "popup", "error"],
    SessionSnapshotResponse: ["session_id", "server_instance", "version", "protocol", "focused_space_id", "focused_tab_id", "focused_pane_id", "spaces", "tabs", "panes", "agents", "herdr_shell"],
    TerminalOpenRequest: ["session_id", "pane_id", "target_kind", "mode", "takeover", "cols", "rows", "cell_width_px", "cell_height_px"],
  },
  lengths: {
    "BrowserViewSnapshot.targets": { max: 10_000 }, "BrowserViewFileCommand[choose].selection_ids": { max: 64 },
    "BrowserViewCaptureCommand.annotation_ids": { max: 64 }, "BrowserViewDraftAnnotation.points": { max: 8192 },
    "BrowserElementEvidence.locators": { max: 256 }, "BrowserAnnotation.points": { max: 10_000 },
    "BrowserFeedbackCapture.annotations": { max: 10_000 }, "BrowserFeedbackCapture.pending_ids": { max: 10_000 },
    "BrowserFeedbackResponse.captures": { max: 256 }, "BrowserFeedbackAckRequest.ids": { max: 10_000 },
    "BrowserFeedbackSendRequest.ids": { max: 10_000 }, "BrowserFeedbackDeliveryStatus.selected_ids": { max: 64 },
    "BrowserFeedbackLookup.deliveries": { max: 64 },
  },
  fields: {
    "BrowserTarget.session_id": nonempty, "BrowserTarget.tab_id": (v) => v === null || nonempty(v), "BrowserTarget.pane_id": (v) => v === null || nonempty(v),
    "BrowserAssociation.tab_id": nonempty,
    "BrowserCleanupScope[tab].session_id": id, "BrowserCleanupScope[tab].tab_id": id,
    "BrowserCleanupFailure.association_key": hash, "BrowserCleanupRetryRequest.association_key": hash,
    "BrowserViewViewportRequest.css_width": (v) => v > 0 && v <= 2560,
    "BrowserViewViewportRequest.css_height": (v) => v > 0 && v <= 1600,
    "BrowserViewViewportRequest.device_pixel_ratio": positive, "BrowserViewOpenRequest.client_id": id,
    "BrowserViewIdentity.association_key": id, "BrowserViewIdentity.browser_incarnation": id, "BrowserViewIdentity.view_id": id,
    "BrowserViewTargetSummary.target_id": id, "BrowserViewTargetSummary.opener_target_id": nullableId,
    "BrowserViewDocumentState.target_id": id, "BrowserViewDocumentState.frame_id": id,
    "BrowserViewViewportState.css_width": positive, "BrowserViewViewportState.css_height": positive,
    "BrowserViewViewportState.visual_scale": positive, "BrowserViewViewportState.page_scale": positive, "BrowserViewViewportState.device_pixel_ratio": positive,
    "BrowserViewCursorState.target_id": id,
    "BrowserViewBlocker.blocker_id": id, "BrowserViewBlocker.target_id": id,
    "BrowserViewControlState.controller_view_id": nullableId,
    "BrowserViewFrameGrant.view_id": id, "BrowserViewFrameGrant.grant": (v) => nonempty(v) && text(v),
    "BrowserViewFrameDescriptor.target_id": id,
    "BrowserViewFrameDescriptor.image_width": (v) => v > 0 && v <= 2560,
    "BrowserViewFrameDescriptor.image_height": (v) => v > 0 && v <= 1600,
    "BrowserViewFrameDescriptor.viewport_css_width": positive, "BrowserViewFrameDescriptor.viewport_css_height": positive,
    "BrowserViewFrameDescriptor.jpeg_length": (v) => v > 0 && v <= 6 * 1024 * 1024,
    "BrowserViewSnapshot.displayed_target_id": nullableId, "BrowserViewEventMetadata.view_id": id,
    "BrowserViewEvent[targets_changed].displayed_target_id": nullableId,
    "BrowserViewLocation.target_id": id, "BrowserViewDocumentCommandContext.target_id": id,
    "BrowserViewTextInput.text": text, "BrowserViewCompositionInput.text": text,
    "BrowserViewClipboardCommand[paste].text": text,
    "BrowserViewTabCommand[select].target_id": id, "BrowserViewTabCommand[close].target_id": id,
    "BrowserViewDialogCommand[accept].text": (v) => v === null || text(v),
    "BrowserViewFileCommand[choose].selection_ids": ids,
    "BrowserViewInspectResult.frame_id": id, "BrowserViewCaptureCommand.draft_id": id, "BrowserViewCaptureCommand.annotation_ids": ids,
    "BrowserViewDraftAnnotation.id": id, "BrowserViewDraftState.draft_id": id, "BrowserViewDraftState.target_id": id,
    "BrowserViewDraftEditorState.note_text": (v) => v.length <= 4000,
    "BrowserViewPendingCapture.association_key": id, "BrowserViewPendingCapture.browser_incarnation": id,
    "BrowserViewPendingCapture.capture_id": id, "BrowserViewPendingCapture.draft_id": id,
    "BrowserViewPendingCapture.annotation_ids": ids, "BrowserViewPendingCapture.last_error": (v) => v === null || text(v),
    "BrowserCaptureSaved.capture_id": id, "BrowserCaptureSaved.annotation_ids": ids,
    "BrowserViewDraftCommand[open].draft_id": nullableId, "BrowserViewDraftCommand[remove_annotation].annotation_id": id,
    "BrowserViewDraftCommand[save_capture].annotation_ids": ids,
    "BrowserCaptureSubmission.association_key": id, "BrowserCaptureSubmission.browser_instance": id, "BrowserCaptureSubmission.capture_id": id,
    "BrowserDraftRecoveryAction[set_editor].draft_id": id, "BrowserDraftRecoveryAction[upsert_annotation].draft_id": id,
    "BrowserDraftRecoveryAction[remove_annotation].draft_id": id, "BrowserDraftRecoveryAction[remove_annotation].annotation_id": id,
    "BrowserDraftRecoveryAction[discard_draft].draft_id": id,
    "BrowserViewCommand[dialog].blocker_id": id, "BrowserViewCommand[file].blocker_id": id,
    "BrowserViewCommand[download].blocker_id": id, "BrowserViewCommand[permission].blocker_id": id,
    "BrowserViewCommand[draft].draft_id": nullableId,
    "BrowserViewCommandRequest.view_id": id, "BrowserViewCommandRequest.request_id": id,
    "BrowserViewCommandOutcome[capture_prepared].capture_id": id,
    "BrowserViewCommandResponse.view_id": id, "BrowserViewCommandResponse.request_id": id,
    "BrowserRect.width": (v) => v >= 0, "BrowserRect.height": (v) => v >= 0,
    "BrowserPageEvidence.tab_id": (v) => v === null || v === undefined || v >= 0,
    "BrowserFeedbackAckRequest.ids": nonemptyIds, "BrowserFeedbackSendRequest.ids": nonemptyIds,
    "BrowserFeedbackImageRequest.capture_id": nonempty, "BrowserFeedbackSendRequest.operation_id": nonempty,
    "BrowserFeedbackDeliveryStatus.capture_id": nonempty, "BrowserFeedbackDeliveryStatus.operation_id": nonempty,
    "BrowserFeedbackDeliveryStatus.selected_ids": nonemptyIds, "BrowserFeedbackDeliveryStatus.message": (v) => v.length <= 4096,
    "BrowserFeedbackImage.mime_type": nonempty, "BrowserFeedbackImage.data_base64": base64,
    "BrowserFeedbackResponse.pending_count": (v) => v <= 0xffffffff,
    "BrowserFeedbackSendResponse.pending_count": (v) => v <= 0xffffffff,
    "BrowserFeedbackAck.remaining": (v) => v <= 0xffffffff,
    "TerminalStreamMessage[frame].encoding": (v) => v === "ansi",
    "SessionSnapshotResponse.server_instance": (v) => /^[0-9a-f]{16}$/.test(v),
    "PaneMoveDestination[existing_tab].ratio": ratio, "ResourceMutationRequest[pane_split].ratio": ratio,
    "CreatedPane.pane_id": id, "CreatedPane.terminal_id": id, "CreatedPane.space_id": id, "CreatedPane.tab_id": id,
    "TerminalOpenRequest.cols": positive, "TerminalOpenRequest.rows": positive,
    "TerminalCommand[terminal.input].bytes": (v) => v === null || base64(v),
    "TerminalStreamMessage[frame].seq": (v) => /^[0-9]+$/.test(v), "TerminalStreamMessage[frame].bytes": base64,
  },
  checks: {
    BrowserTarget: { target: (v) => (v.tab_id === null) !== (v.pane_id === null) },
    BrowserViewFrameDescriptor: { pixels: (v) => v.image_width * v.image_height <= 2560 * 1600 },
    BrowserViewSnapshot: { grant_stream: (v) => v.frame_grant === null || (v.frame_grant.view_id === v.identity.view_id && v.frame_grant.stream_epoch === v.identity.stream_epoch) },
    "BrowserViewEvent[attached]": { attached_identity: (v) => v.snapshot.identity.view_id === v.metadata.view_id && v.snapshot.identity.stream_epoch === v.metadata.stream_epoch && v.snapshot.metadata_sequence === v.metadata.metadata_sequence },
    BrowserFeedbackSendRequest: { no_recipient: (_v, original) => !("recipient" in original) },
    ResourceMutationResponse: {
      snapshot_session: (v) => v.session_id === v.snapshot.session_id,
      created_identity: (v) => {
        const created = v.created;
        return created === null || (
          v.snapshot.panes.some((p) => p.id === created.pane_id && p.terminal_id === created.terminal_id && p.tab_id === created.tab_id && p.space_id === created.space_id)
          && v.snapshot.tabs.some((t) => t.id === created.tab_id && t.space_id === created.space_id)
          && v.snapshot.spaces.some((s) => s.id === created.space_id)
        );
      },
    },
    "SessionStreamMessage[snapshot]": { session: (v) => v.session_id === v.snapshot.session_id },
    TerminalOpenRequest: { herdr_ids: (v) => sessionId(v.session_id) && resourceId(v.pane_id) },
    "TerminalCommand[terminal.input]": { exclusive: (v) => (v.text !== null) !== (v.bytes !== null) },
    "TerminalCommand[terminal.mouse]": { button: (v) => v.kind === "moved" ? v.button === null : v.button !== null },
    "TerminalStreamMessage[frame]": { sequence: (v) => { try { BigInt(v.seq); return true; } catch { return false; } } },
  },
};

// The inline command outcome (:1319) differs from the feedback lookup inventory (:1155).
// Overrides reuse the descriptor and preserve that occurrence's original guard and bound.
const inventoryWire: TypedWirePolicy = { ...wire, order: { ...order, BrowserViewDraftInventory: ["drafts", "active_draft_limit", "pending_capture"] } };
const lookupInventoryWire: TypedWirePolicy = { ...wire, lengths: { ...wire.lengths, "BrowserViewDraftInventory.drafts": { max: 8 } } };
const captureProvenanceWire: TypedWirePolicy = {
  ...wire,
  fields: { ...wire.fields, "BrowserInlineCaptureProvenance.target_id": id, "BrowserInlineCaptureProvenance.frame_id": id },
};
// Feedback contexts preserved provenance references; save commands reconstructed them.
const contextProvenanceWire: TypedWirePolicy = {
  ...wire,
  raw: new Set([...wire.raw!, "BrowserInlineCaptureProvenance"]),
};
export const CLIENT = definePolicy({
  wire: { ...wire, overrides: {
    "BrowserViewCommandOutcome[draft_inventory].inventory": inventoryWire,
    "BrowserFeedbackLookup.drafts": lookupInventoryWire,
    "BrowserViewDraftCommand[save_capture].provenance": captureProvenanceWire,
    "BrowserCaptureContext.inline_provenance": contextProvenanceWire,
  } },
  message: messageTable(messages, "Client response is malformed", absorb),
});
